DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4847
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4820
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4814
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4827
ERROR:django.request:Internal Server Error: /APIHandling/
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\APIHandling\views.py", line 42, in index
    latest_question_list = Bike.objects.create(name='Shep', data={'breed': 'collie'})
  File "C:\Python37\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\db\models\query.py", line 411, in create
    obj = self.model(**kwargs)
  File "C:\Python37\lib\site-packages\django\db\models\base.py", line 485, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % kwarg)
TypeError: 'data' is an invalid keyword argument for this function
ERROR:django.request:Internal Server Error: /APIHandling/
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\APIHandling\views.py", line 32, in index
    latest_question_list = Bike.objects.create(name='Shep', data={'breed': 'collie'})
  File "C:\Python37\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\db\models\query.py", line 411, in create
    obj = self.model(**kwargs)
  File "C:\Python37\lib\site-packages\django\db\models\base.py", line 485, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % kwarg)
TypeError: 'data' is an invalid keyword argument for this function
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4832
ERROR:django.request:Internal Server Error: /APIHandling/
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\APIHandling\views.py", line 33, in index
    latest_question_list = Bike.objects.create(name='Shep', data={'breed': 'collie'})
  File "C:\Python37\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\db\models\query.py", line 411, in create
    obj = self.model(**kwargs)
  File "C:\Python37\lib\site-packages\django\db\models\base.py", line 485, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % kwarg)
TypeError: 'data' is an invalid keyword argument for this function
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4841
ERROR:django.request:Internal Server Error: /APIHandling/
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\APIHandling\views.py", line 52, in index
    pushNewData()
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\APIHandling\views.py", line 32, in pushNewData
    number = data.get('number', None)
AttributeError: 'list' object has no attribute 'get'
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4837
ERROR:django.request:Internal Server Error: /APIHandling/
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\APIHandling\views.py", line 53, in index
    pushNewData()
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\APIHandling\views.py", line 33, in pushNewData
    number = data.get('number', None)
AttributeError: 'list' object has no attribute 'get'
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4837
ERROR:django.request:Internal Server Error: /APIHandling/
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\APIHandling\views.py", line 53, in index
    pushNewData()
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\APIHandling\views.py", line 31, in pushNewData
    data = json.loads(getLatestData())
  File "C:\Python37\lib\json\__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not list
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4836
ERROR:django.request:Internal Server Error: /APIHandling/
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\APIHandling\views.py", line 53, in index
    pushNewData()
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\APIHandling\views.py", line 31, in pushNewData
    data = json.loads(getLatestData())
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\APIHandling\views.py", line 22, in getLatestData
    dublinbike_data = json.dumps(dublinbike_data_request.text, object_pairs_hook=OrderedDict)
  File "C:\Python37\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
TypeError: __init__() got an unexpected keyword argument 'object_pairs_hook'
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4836
ERROR:django.request:Internal Server Error: /APIHandling/
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\APIHandling\views.py", line 53, in index
    pushNewData()
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\APIHandling\views.py", line 33, in pushNewData
    number = data.get('number', None)
AttributeError: 'str' object has no attribute 'get'
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4858
ERROR:django.request:Internal Server Error: /APIHandling/
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\APIHandling\views.py", line 57, in index
    pushNewData()
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\APIHandling\views.py", line 34, in pushNewData
    value = data[key]
TypeError: list indices must be integers or slices, not dict
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4826
ERROR:django.request:Internal Server Error: /APIHandling/
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\APIHandling\views.py", line 57, in index
    pushNewData()
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\APIHandling\views.py", line 34, in pushNewData
    value = data[0][key]
TypeError: unhashable type: 'dict'
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4851
ERROR:django.request:Internal Server Error: /APIHandling/
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\APIHandling\views.py", line 56, in index
    pushNewData()
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\APIHandling\views.py", line 34, in pushNewData
    data[0][key]
TypeError: unhashable type: 'dict'
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4851
ERROR:django.request:Internal Server Error: /APIHandling/
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\APIHandling\views.py", line 56, in index
    pushNewData()
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\APIHandling\views.py", line 34, in pushNewData
    data[key]
TypeError: list indices must be integers or slices, not dict
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4851
ERROR:django.request:Internal Server Error: /APIHandling/
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\APIHandling\views.py", line 56, in index
    pushNewData()
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\APIHandling\views.py", line 36, in pushNewData
    number = data.get('number', None)
AttributeError: 'list' object has no attribute 'get'
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4851
ERROR:django.request:Internal Server Error: /APIHandling/
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\APIHandling\views.py", line 58, in index
    pushNewData()
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\APIHandling\views.py", line 36, in pushNewData
    print(value + key)
TypeError: unsupported operand type(s) for +: 'int' and 'str'
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4847
ERROR:django.request:Internal Server Error: /APIHandling/
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\APIHandling\views.py", line 58, in index
    pushNewData()
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\APIHandling\views.py", line 38, in pushNewData
    number = data.get('number', None)
AttributeError: 'list' object has no attribute 'get'
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4847
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4847
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4841
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4841
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4826
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4859
ERROR:django.request:Internal Server Error: /APIHandling/
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\APIHandling\views.py", line 57, in index
    pushNewData()
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\APIHandling\views.py", line 52, in pushNewData
    available_bikes=available_bikes, status=status, last_update=last_update)
  File "C:\Python37\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\db\models\query.py", line 411, in create
    obj = self.model(**kwargs)
  File "C:\Python37\lib\site-packages\django\db\models\base.py", line 485, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % kwarg)
TypeError: 'position_lng' is an invalid keyword argument for this function
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4844
ERROR:django.request:Internal Server Error: /APIHandling/
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\APIHandling\views.py", line 57, in index
    pushNewData()
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\APIHandling\views.py", line 52, in pushNewData
    available_bikes=available_bikes, status=status, last_update=last_update)
  File "C:\Python37\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\db\models\query.py", line 411, in create
    obj = self.model(**kwargs)
  File "C:\Python37\lib\site-packages\django\db\models\base.py", line 485, in __init__
    raise TypeError("'%s' is an invalid keyword argument for this function" % kwarg)
TypeError: 'position_lng' is an invalid keyword argument for this function
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4843
ERROR:django.request:Internal Server Error: /APIHandling/
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\APIHandling\views.py", line 57, in index
    pushNewData()
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\APIHandling\views.py", line 52, in pushNewData
    available_bikes=available_bikes, status=status, last_update=last_update)
  File "C:\Python37\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\db\models\query.py", line 413, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Python37\lib\site-packages\django\db\models\base.py", line 718, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Python37\lib\site-packages\django\db\models\base.py", line 748, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "C:\Python37\lib\site-packages\django\db\models\base.py", line 831, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "C:\Python37\lib\site-packages\django\db\models\base.py", line 869, in _do_insert
    using=using, raw=raw)
  File "C:\Python37\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\db\models\query.py", line 1136, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "C:\Python37\lib\site-packages\django\db\models\sql\compiler.py", line 1288, in execute_sql
    for sql, params in self.as_sql():
  File "C:\Python37\lib\site-packages\django\db\models\sql\compiler.py", line 1241, in as_sql
    for obj in self.query.objs
  File "C:\Python37\lib\site-packages\django\db\models\sql\compiler.py", line 1241, in <listcomp>
    for obj in self.query.objs
  File "C:\Python37\lib\site-packages\django\db\models\sql\compiler.py", line 1240, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "C:\Python37\lib\site-packages\django\db\models\sql\compiler.py", line 1182, in prepare_value
    value = field.get_db_prep_save(value, connection=self.connection)
  File "C:\Python37\lib\site-packages\django\db\models\fields\__init__.py", line 1563, in get_db_prep_save
    return connection.ops.adapt_decimalfield_value(self.to_python(value), self.max_digits, self.decimal_places)
  File "C:\Python37\lib\site-packages\django\db\models\fields\__init__.py", line 1554, in to_python
    return decimal.Decimal(value)
TypeError: conversion from dict to Decimal is not supported
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4825
ERROR:django.request:Internal Server Error: /APIHandling/
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\APIHandling\views.py", line 57, in index
    pushNewData()
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\APIHandling\views.py", line 52, in pushNewData
    available_bikes=available_bikes, status=status, last_update=last_update)
  File "C:\Python37\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\db\models\query.py", line 413, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Python37\lib\site-packages\django\db\models\base.py", line 718, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Python37\lib\site-packages\django\db\models\base.py", line 748, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "C:\Python37\lib\site-packages\django\db\models\base.py", line 831, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "C:\Python37\lib\site-packages\django\db\models\base.py", line 869, in _do_insert
    using=using, raw=raw)
  File "C:\Python37\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\db\models\query.py", line 1136, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "C:\Python37\lib\site-packages\django\db\models\sql\compiler.py", line 1288, in execute_sql
    for sql, params in self.as_sql():
  File "C:\Python37\lib\site-packages\django\db\models\sql\compiler.py", line 1241, in as_sql
    for obj in self.query.objs
  File "C:\Python37\lib\site-packages\django\db\models\sql\compiler.py", line 1241, in <listcomp>
    for obj in self.query.objs
  File "C:\Python37\lib\site-packages\django\db\models\sql\compiler.py", line 1240, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "C:\Python37\lib\site-packages\django\db\models\sql\compiler.py", line 1182, in prepare_value
    value = field.get_db_prep_save(value, connection=self.connection)
  File "C:\Python37\lib\site-packages\django\db\models\fields\__init__.py", line 790, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "C:\Python37\lib\site-packages\django\db\models\fields\__init__.py", line 1429, in get_db_prep_value
    value = self.get_prep_value(value)
  File "C:\Python37\lib\site-packages\django\db\models\fields\__init__.py", line 1408, in get_prep_value
    value = super().get_prep_value(value)
  File "C:\Python37\lib\site-packages\django\db\models\fields\__init__.py", line 1268, in get_prep_value
    return self.to_python(value)
  File "C:\Python37\lib\site-packages\django\db\models\fields\__init__.py", line 1369, in to_python
    parsed = parse_datetime(value)
  File "C:\Python37\lib\site-packages\django\utils\dateparse.py", line 106, in parse_datetime
    match = datetime_re.match(value)
TypeError: expected string or bytes-like object
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4820
ERROR:django.request:Internal Server Error: /APIHandling/
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\APIHandling\views.py", line 58, in index
    pushNewData()
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\APIHandling\views.py", line 48, in pushNewData
    last_update = datetime.datetime.fromtimestamp(row['last_update'])
OSError: [Errno 22] Invalid argument
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4817
ERROR:django.request:Internal Server Error: /APIHandling/
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\APIHandling\views.py", line 59, in index
    pushNewData()
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\APIHandling\views.py", line 49, in pushNewData
    last_update = datetime.datetime.fromtimestamp(row['last_update'])
OSError: [Errno 22] Invalid argument
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4817
ERROR:django.request:Internal Server Error: /APIHandling/
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\APIHandling\views.py", line 59, in index
    pushNewData()
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\APIHandling\views.py", line 48, in pushNewData
    print(datetime.datetime.fromtimestamp(row['last_update']))
OSError: [Errno 22] Invalid argument
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4810
ERROR:django.request:Internal Server Error: /APIHandling/
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\APIHandling\views.py", line 59, in index
    pushNewData()
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\APIHandling\views.py", line 48, in pushNewData
    print(datetime.datetime.fromtimestamp(str(row['last_update'])))
TypeError: an integer is required (got type str)
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4810
ERROR:django.request:Internal Server Error: /APIHandling/
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\APIHandling\views.py", line 59, in index
    pushNewData()
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\APIHandling\views.py", line 48, in pushNewData
    print(datetime.datetime.fromtimestamp(int(row['last_update'])))
OSError: [Errno 22] Invalid argument
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4803
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4838
ERROR:django.request:Internal Server Error: /APIHandling/
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\APIHandling\views.py", line 58, in index
    latest_question_list = []
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\APIHandling\views.py", line 49, in pushNewData
OSError: [Errno 22] Invalid argument
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4845
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4840
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4816
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4831
WARNING:django.request:Not Found: /
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4822
WARNING:django.request:Not Found: /
WARNING:django.request:Not Found: /
WARNING:django.request:Not Found: /
WARNING:django.request:Not Found: /bike
WARNING:django.request:Not Found: /bike
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4823
ERROR:django.request:Internal Server Error: /Bike/
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: relation "Bike_bike" does not exist
LINE 1: INSERT INTO "Bike_bike" ("number", "contract_name", "name", ...
                    ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\Bike\views.py", line 35, in index
    pushNewData()
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\Bike\views.py", line 31, in pushNewData
    available_bikes=available_bikes, status=status, last_update=last_update)
  File "C:\Python37\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\db\models\query.py", line 413, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Python37\lib\site-packages\django\db\models\base.py", line 718, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Python37\lib\site-packages\django\db\models\base.py", line 748, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "C:\Python37\lib\site-packages\django\db\models\base.py", line 831, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "C:\Python37\lib\site-packages\django\db\models\base.py", line 869, in _do_insert
    using=using, raw=raw)
  File "C:\Python37\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python37\lib\site-packages\django\db\models\query.py", line 1136, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "C:\Python37\lib\site-packages\django\db\models\sql\compiler.py", line 1289, in execute_sql
    cursor.execute(sql, params)
  File "C:\Python37\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "C:\Python37\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Python37\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Python37\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Python37\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Python37\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "Bike_bike" does not exist
LINE 1: INSERT INTO "Bike_bike" ("number", "contract_name", "name", ...
                    ^

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4814
ERROR:django.request:Internal Server Error: /Bike/
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\Bike\views.py", line 35, in index
    pushNewData()
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\Bike\views.py", line 32, in pushNewData
    b.save()
NameError: name 'b' is not defined
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4814
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4823
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4823
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4817
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4817
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4838
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4844
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4833
ERROR:django.request:Internal Server Error: /Bike/
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\Bike\views.py", line 34, in index
    template = loader.get_template('Bike/index.html')
  File "C:\Python37\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: Bike/index.html
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4847
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4847
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4847
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4844
ERROR:django.request:Internal Server Error: /Bike/
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\Bike\views.py", line 34, in index
    template = loader.get_template('bike.html')
  File "C:\Python37\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: bike.html
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4834
WARNING:django.request:Not Found: /
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\Main\views.py", line 8, in index
    return HttpResponse(template.render(request))
  File "C:\Python37\lib\site-packages\django\template\backends\django.py", line 59, in render
    context = make_context(context, request, autoescape=self.backend.engine.autoescape)
  File "C:\Python37\lib\site-packages\django\template\context.py", line 270, in make_context
    raise TypeError('context must be a dict rather than %s.' % context.__class__.__name__)
TypeError: context must be a dict rather than WSGIRequest.
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\Main\views.py", line 8, in index
    return HttpResponse(template.render([],request))
  File "C:\Python37\lib\site-packages\django\template\backends\django.py", line 59, in render
    context = make_context(context, request, autoescape=self.backend.engine.autoescape)
  File "C:\Python37\lib\site-packages\django\template\context.py", line 270, in make_context
    raise TypeError('context must be a dict rather than %s.' % context.__class__.__name__)
TypeError: context must be a dict rather than list.
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\Main\views.py", line 7, in index
    template = loader.get_template('index.html')
  File "C:\Python37\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\Main\views.py", line 8, in index
    return HttpResponse(template.render({},request))
  File "C:\Python37\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Python37\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Python37\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Python37\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Python37\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python37\lib\site-packages\django\template\defaulttags.py", line 442, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Python37\lib\site-packages\django\urls\base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "C:\Python37\lib\site-packages\django\urls\resolvers.py", line 622, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for '' not found. '' is not a valid view function or pattern name.
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\Main\views.py", line 8, in index
    return HttpResponse(template.render({}, request))
  File "C:\Python37\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Python37\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Python37\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Python37\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Python37\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python37\lib\site-packages\django\template\defaulttags.py", line 442, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Python37\lib\site-packages\django\urls\base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "C:\Python37\lib\site-packages\django\urls\resolvers.py", line 622, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'Bike.views.index' not found. 'Bike.views.index' is not a valid view function or pattern name.
WARNING:django.request:Not Found: /Bike/bike_data
WARNING:django.request:Not Found: /bike_data
WARNING:django.request:Not Found: /bike_data
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4841
ERROR:django.request:Internal Server Error: /Bike/
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python37\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\romaa\Trinity\CS7CS3-Advanced Software Engineering\Sustainable_City_Management\Bike\views.py", line 39, in index
    return HttpResponse(template.render(context, request))
  File "C:\Python37\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Python37\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Python37\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Python37\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Python37\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python37\lib\site-packages\django\template\defaulttags.py", line 442, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Python37\lib\site-packages\django\urls\base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "C:\Python37\lib\site-packages\django\urls\resolvers.py", line 622, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'bike_data' not found. 'bike_data' is not a valid view function or pattern name.
WARNING:django.request:Not Found: /bike_data
WARNING:django.request:Not Found: /Bike/Bike/bike_data
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4835
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4835
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4823
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4806
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4822
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4826
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4826
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4810
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4819
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4819
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4836
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4836
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4850
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4850
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4853
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4862
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4860
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4860
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4860
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4851
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4864
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4864
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4864
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4830
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4822
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4819
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4873
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4848
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4848
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4848
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4848
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4842
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4842
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4834
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4844
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4839
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4844
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4844
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4862
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4862
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4862
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4862
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4865
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4869
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4869
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4872
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4872
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4864
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4864
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4841
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4835
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4835
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4852
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4858
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4875
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4875
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4871
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4871
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4864
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4864
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4863
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4863
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4852
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4825
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4825
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4831
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4847
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4762
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4763
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4772
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4772
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4772
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4768
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4773
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4789
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4789
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4791
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4791
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4791
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4791
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4802
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4802
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4805
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4803
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4791
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4791
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4788
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4789
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4790
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4790
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4791
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4791
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4791
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4791
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4791
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4791
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4784
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4793
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4787
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4787
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4787
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4830
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4799
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4805
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4771
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4783
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4783
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4783
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4783
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4766
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4763
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4763
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4774
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4777
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4777
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4777
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4785
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4785
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.jcdecaux.com:443
DEBUG:urllib3.connectionpool:https://api.jcdecaux.com:443 "GET /vls/v1/stations?contract=Dublin&apiKey=29374861957fe56e1b065c24f9cf06f84ae8dce2 HTTP/1.1" 200 4785
